import type { Song } from "../library/song.types";
import type { DiscordTitleCleanup } from "../discord/discord.types";
import { makeLocalId } from "../../shared/storage/localStorage";
import { collapseSpaces, lower, normalizeUiText, safeNumber } from "../../shared/utils/format";

export function removeUrlNoise(text: string) { return collapseSpaces(String(text||"").replace(/https?:\/\/\S+/gi," ").replace(/www\.\S+/gi," ").replace(/(?:youtube|youtu\.be|soundcloud|spotify|bandcamp|tiktok|instagram|discord)\S*/gi," ")); }
export function stripAudioExtension(fileName = "") { return normalizeUiText(fileName).replace(/\.(mp3|flac|wav|m4a|aac|ogg|opus|webm|mp4|aiff|alac)$/i,"").replace(/[_]+/g," ").replace(/\s+/g," ").trim(); }
export function stripTrackNumber(text:string){return collapseSpaces(text.replace(/^\s*(?:track\s*)?\d{1,3}\s*[.\-_)]+\s*/i,"").replace(/^\s*cd\s*\d+\s*[.\-_)]+\s*/i,""));}
export function stripDuplicateCopySuffix(text:string){let next=text;for(let i=0;i<5;i+=1){const cleaned=next.replace(/\s*\((?:copy|duplicate|\d+)\)\s*$/gi,"").replace(/\s*\[(?:copy|duplicate|\d+)\]\s*$/gi,"").replace(/\s+-\s+copy\s*$/gi,"").replace(/\s+copy\s*$/gi,"").trim();if(cleaned===next)break;next=cleaned;}return next;}
export function removeBracketNoise(text:string,strength:DiscordTitleCleanup="heavy"){const words=strength==="light"?"official|audio|video|lyrics?|lyric video|visualizer|hq|hd|4k|320kbps":"official|audio|video|lyrics?|lyric video|visualizer|hq|hd|4k|320kbps|slowed|reverb|slowed and reverb|sped up|nightcore|bass boosted|extended|remaster(?:ed)?|clean|edit|loop|tik ?tok|full song";return text.replace(new RegExp(`\\s*[\\[(][^\\])]*(?:${words})[^\\])]*[\\])]`,"gi")," ");}
export function removeLooseNoiseWords(text:string,strength:DiscordTitleCleanup="heavy"){if(strength!=="heavy")return collapseSpaces(text);return collapseSpaces(text.replace(/\b(?:official\s+music\s+video|official\s+video|official\s+audio|lyric\s+video|lyrics?\s+video)\b/gi," ").replace(/\b(?:visualizer|hq|hd|4k|320kbps|full\s+song)\b/gi," ").replace(/\b(?:slowed\s*(?:and|&)?\s*reverb|slowedandreverb|slowedreverb|sped\s*up|bass\s*boosted|nightcore|remaster(?:ed)?|extended\s+mix)\b/gi," ").replace(/\b(?:from\s+tiktok|tiktok\s+version|youtube\s+rip)\b/gi," "));}
export function cleanupSongTitle(rawTitle:string,strength:DiscordTitleCleanup="heavy"){let text=removeUrlNoise(normalizeUiText(rawTitle||"untitled"));text=stripAudioExtension(text).replace(/[_]+/g," ").replace(/[–—]+/g," - ").replace(/[“”]/g,'"').replace(/[‘’]/g,"'");text=stripTrackNumber(stripDuplicateCopySuffix(text));text=removeBracketNoise(text,strength);text=removeLooseNoiseWords(text,strength);if(strength==="heavy")text=text.replace(/\s+[|/]+\s*(?:slowed|reverb|sped up|nightcore|lyrics?|official|audio|video).*$/i,"").replace(/\s+-\s*(?:slowed|reverb|sped up|nightcore|lyrics?|official|audio|video).*$/i,"");return collapseSpaces(text.replace(/\s*[{}\[\]]\s*/g," ").replace(/\s*\(\s*\)\s*/g," ").replace(/(^|\s)[+~]+(?=\s|$)/g," ").replace(/\s+[–—-]\s*$/g," "))||"untitled";}
export function shortenWords(text:string,maxWords=7){const words=collapseSpaces(text).split(" ").filter(Boolean);return words.length?words.slice(0,maxWords).join(" "):"untitled";}
export function prettyTitle(rawTitle:string,maxWords=7){return lower(shortenWords(cleanupSongTitle(rawTitle,"heavy"),maxWords));}
export function heroTitleDensityClass(title:string){const letters=collapseSpaces(title||"").replace(/[^a-z0-9]/gi,"");if(letters.length<=5)return"heroTitleTiny";if(letters.length<=11)return"heroTitleShort";if(letters.length>=32)return"heroTitleLong";return"heroTitleNormal";}
export function previewTitle(rawTitle:string,cleanup:DiscordTitleCleanup,maxWords=7){if(cleanup==="off")return lower(shortenWords(collapseSpaces(rawTitle||"local song"),maxWords));if(cleanup==="light")return lower(shortenWords(cleanupSongTitle(rawTitle||"local song","light"),maxWords));return lower(shortenWords(cleanupSongTitle(rawTitle,"heavy"),maxWords));}
export function compactSongKey(text:string){return lower(cleanupSongTitle(text||"","heavy")).replace(/\b(official|audio|lyrics|lyric|video|visualizer|remix|remastered|slowed|reverb|sped|nightcore|lofi)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
export type SongSearchEntry={song:Song;title:string;artist:string;album:string;fileName:string;filePath:string;compactTitle:string;compactArtist:string;compactAlbum:string;haystack:string;tokens:string[]};
export type SearchQueryInfo={raw:string;clean:string;compact:string;terms:string[]};
export function normalizeSearchText(value:unknown){return String(value??"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[_\-.]+/g," ").replace(/[()[\]{}]+/g," ").replace(/[^a-zA-Z0-9\s:/]+/g," ").toLowerCase().replace(/\s+/g," ").trim();}
export function splitSearchTerms(query:string){return normalizeSearchText(query).split(" ").filter(Boolean).slice(0,14);}
export function prepareSearchQuery(query:string):SearchQueryInfo{const clean=normalizeSearchText(query);return{raw:query,clean,compact:compactSongKey(clean),terms:clean?splitSearchTerms(clean):[]};}
export function fileNameFromPath(filePath=""){return String(filePath||"").split(/[\\/]/).pop()||"";}
export function cleanMetadataField(value:unknown,fallback:string){const cleaned=cleanupSongTitle(removeUrlNoise(String(value??"")),"light").replace(/\b(?:unknown|n\/a|null|undefined)\b$/i,"").replace(/\s+/g," ").trim();return lower(cleaned||fallback);}
export function looksUnknownMeta(value:unknown){const text=normalizeSearchText(value);return !text||["unknown","unknown artist","unknown album","n a","na","null","undefined"].includes(text);}
export function cleanArtistName(value:unknown){return cleanMetadataField(value,"unknown artist").replace(/^by\s+/i,"").replace(/\s+(?:official|topic|vevo)$/i,"").trim()||"unknown artist";}
export function cleanTrackName(value:unknown,fallback="untitled"){return cleanMetadataField(value,fallback).replace(/^[-–—|/]+\s*/,"").replace(/\s*[-–—|/]+$/,"").trim()||fallback;}
export function scoreArtistGuess(text:string){const clean=normalizeSearchText(text);let score=0;if(/\b(feat|ft|prod|records|music|official|topic|vevo)\b/i.test(clean))score+=2;if(clean.split(" ").length<=5)score+=1;if(/^[a-z0-9 ._&'!]+$/i.test(text))score+=1;return score;}
export function splitArtistTitleCandidate(value:string){const base=cleanupSongTitle(stripAudioExtension(value),"light");for(const separator of [" - "," | "," / "," ~ "]){if(!base.includes(separator))continue;const pieces=base.split(separator).map(collapseSpaces).filter(Boolean);if(pieces.length<2)continue;const left=pieces[0],right=pieces.slice(1).join(separator===" - "?" - ":" ");if(left.length>=2&&right.length>=2)return{artist:cleanArtistName(left),title:cleanTrackName(right)};}const by=base.match(/^(.{2,120}?)\s+by\s+(.{2,80}?)(?:\s+(?:version|cover|remix|edit))?$/i);return by?{title:cleanTrackName(by[1]),artist:cleanArtistName(by[2])}:null;}
export function smartSongMetadata(song:Partial<Song>&Record<string,unknown>,index:number){const fileBase=stripAudioExtension(fileNameFromPath(String(song.filePath||song.url||"")));const fileSplit=splitArtistTitleCandidate(fileBase),titleSplit=splitArtistTitleCandidate(String(song.title||""));let title=looksUnknownMeta(song.title)?"":cleanTrackName(song.title,""),artist=looksUnknownMeta(song.artist)?"":cleanArtistName(song.artist),album=looksUnknownMeta(song.album)?"":cleanMetadataField(song.album,"local files");if(!artist&&titleSplit){title=titleSplit.title;artist=titleSplit.artist;}else if(artist&&titleSplit&&normalizeSearchText(titleSplit.artist)===normalizeSearchText(artist))title=titleSplit.title;if((!title||!artist)&&fileSplit){if(!title)title=fileSplit.title;if(!artist)artist=fileSplit.artist;}if(!title)title=cleanTrackName(fileBase,`track ${index+1}`);if(!artist)artist="unknown artist";if(!album)album="local files";return{title:cleanTrackName(title,`track ${index+1}`),artist:cleanArtistName(artist),album:cleanMetadataField(album,"local files")};}
export function sanitizeSongRecord(song:Partial<Song>&Record<string,unknown>,index:number):Song{const meta=smartSongMetadata(song,index);const sourcePath=String(song.filePath||(song as any).path||"");const rawUrl=String((song as any).playbackUrl||song.url||"");const sourceUrl=sourcePath?"":rawUrl;const fileExists=typeof song.fileExists==="boolean"?song.fileExists:typeof (song as any).exists==="boolean"?(song as any).exists:undefined;return{id:String(song.id||makeLocalId("song")),title:meta.title,artist:meta.artist,album:meta.album,filePath:sourcePath,url:sourceUrl,fileExists,coverPath:song.coverPath??null,coverUrl:song.coverUrl??null,liked:Boolean(song.liked),playCount:Math.floor(safeNumber(song.playCount,0)),duration:safeNumber(song.duration,0),dateAdded:String(song.dateAdded||new Date().toISOString()),lastPlayed:song.lastPlayed??null,volumeGain:typeof song.volumeGain==="number"&&Number.isFinite(song.volumeGain)?song.volumeGain:undefined,playbackPosition:safeNumber(song.playbackPosition,0),customVolume:typeof song.customVolume==="number"&&Number.isFinite(song.customVolume)?song.customVolume:undefined,fileSizeBytes:typeof song.fileSizeBytes==="number"&&Number.isFinite(song.fileSizeBytes)?song.fileSizeBytes:song.sizeBytes,sizeBytes:typeof song.sizeBytes==="number"&&Number.isFinite(song.sizeBytes)?song.sizeBytes:song.fileSizeBytes,bitrate:typeof song.bitrate==="number"&&Number.isFinite(song.bitrate)?song.bitrate:undefined,sampleRate:typeof song.sampleRate==="number"&&Number.isFinite(song.sampleRate)?song.sampleRate:undefined};}
export function sanitizeSongList(input:unknown):Song[]{return Array.isArray(input)?input.filter((item):item is Partial<Song>&Record<string,unknown>=>Boolean(item&&typeof item==="object")).map(sanitizeSongRecord):[];}
export function getMetadataRepairPatch(song:Song):Partial<Song>{const clean=sanitizeSongRecord(song,0),patch:Partial<Song>={};if(clean.title!==song.title)patch.title=clean.title;if(clean.artist!==song.artist)patch.artist=clean.artist;if(clean.album!==song.album)patch.album=clean.album;if(clean.duration!==song.duration)patch.duration=clean.duration;if(clean.playCount!==song.playCount)patch.playCount=clean.playCount;if((song.playbackPosition||0)<0||!Number.isFinite(Number(song.playbackPosition||0)))patch.playbackPosition=0;return patch;}
export function buildSongSearchEntry(song:Song):SongSearchEntry{const raw=stripAudioExtension(fileNameFromPath(song.filePath||song.url||"")),fileName=normalizeSearchText(raw),title=normalizeSearchText(song.title),artist=normalizeSearchText(song.artist),album=normalizeSearchText(song.album),filePath=normalizeSearchText(song.filePath||song.url||""),compactTitle=compactSongKey(song.title||raw),compactArtist=compactSongKey(song.artist||""),compactAlbum=compactSongKey(song.album||"");const haystack=[title,artist,album,fileName,filePath,compactTitle,compactArtist,compactAlbum,song.liked?"liked favorite heart":""].filter(Boolean).join(" ");return{song,title,artist,album,fileName,filePath,compactTitle,compactArtist,compactAlbum,haystack,tokens:Array.from(new Set(haystack.split(" ").filter(Boolean)))};}
export function scoreSongSearch(entry:SongSearchEntry,search:SearchQueryInfo){if(!search.clean||!search.terms.length)return 1;let score=0;if(entry.title===search.clean)score+=280;if(entry.artist===search.clean)score+=190;if(entry.album===search.clean)score+=150;if(entry.title.startsWith(search.clean))score+=165;if(entry.artist.startsWith(search.clean))score+=110;if(entry.album.startsWith(search.clean))score+=78;if(entry.compactTitle.includes(search.compact))score+=100;if(entry.compactArtist.includes(search.compact))score+=48;if(entry.fileName.includes(search.clean))score+=58;if(entry.filePath.includes(search.clean))score+=36;if(entry.haystack.includes(search.clean))score+=44;for(const term of search.terms){if(entry.title.startsWith(term))score+=36;else if(entry.title.includes(term))score+=26;else if(entry.artist.startsWith(term))score+=22;else if(entry.artist.includes(term))score+=18;else if(entry.album.includes(term))score+=14;else if(entry.fileName.includes(term))score+=12;else if(entry.filePath.includes(term))score+=8;else if(entry.tokens.some((token)=>token.startsWith(term)||token.includes(term)))score+=5;else return 0;}score+=Math.min(entry.song.playCount||0,60)/6;if(entry.song.liked)score+=3;return score;}
export function rankSongsForSearch(entries:SongSearchEntry[],query:string){const search=prepareSearchQuery(query);if(!search.clean)return entries.map((entry)=>entry.song);return entries.map((entry,index)=>({entry,index,score:scoreSongSearch(entry,search)})).filter((item)=>item.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).map((item)=>item.entry.song);}
export function prettyMeta(text:string){return lower(collapseSpaces(text))||"unknown artist";}
export function discordArtist(text:string){const value=prettyMeta(text);return !value||value==="unknown"||value==="unknown artist"?"coderpixel :p":value;}
