import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import type { CoverGalleryEntry, CoverMood, CoverStudioProps } from "./cover.types";
import { coverEntryMatches, coverSongMatches, normalizeCoverSearch } from "./cover.utils";
import CoverGalleryImage from "./components/CoverGalleryImage";
import VirtualCoverGalleryGrid from "./components/VirtualCoverGalleryGrid";
import VirtualCoverSongList from "./components/VirtualCoverSongList";

export default function CoverStudio({ ambientStyle, pixelArtBusy, selectedCoverSongs, currentSong, missingCoverSongs = [], coverGalleryMood, coverMoodOptions, coverMoodCounts, coverStats, filteredCoverGalleryAssets, coverPickerSongList, coverSelectedSongIds, CoverComponent, prettyTitle, prettyMeta, pixelArtUrl, coverMoodName, setCoverGalleryMood, randomizeSelectedCovers, randomizeMissingCovers, cleanupCoverCache, rescanPixelArtFolder, selectCurrentSongForCovers, selectVisibleSongsForCovers, setCoverSelectedSongIds, toggleCoverSongSelection, applyCoverAssetToSelection, togglePixelCoverExcluded }: CoverStudioProps) {
  const [coverSearch, setCoverSearch] = useState("");
  const [songSearch, setSongSearch] = useState("");
  const [songFilter, setSongFilter] = useState<"all" | "missing">("all");
  const [previewEntryKey, setPreviewEntryKey] = useState("");
  const [coverToast, setCoverToast] = useState("");
  const [recentCoverEntries, setRecentCoverEntries] = useState<CoverGalleryEntry[]>([]);
  const toastTimerRef = useRef<number | null>(null);
  const deferredCoverSearch = normalizeCoverSearch(useDeferredValue(coverSearch));
  const deferredSongSearch = normalizeCoverSearch(useDeferredValue(songSearch));
  const selectedCount = selectedCoverSongs.length || (currentSong ? 1 : 0);
  const randomizeDisabled = pixelArtBusy || (!selectedCoverSongs.length && !currentSong);

  const visibleGalleryAssets = useMemo(() => deferredCoverSearch ? filteredCoverGalleryAssets.filter((entry) => coverEntryMatches(entry, deferredCoverSearch, coverMoodName)) : filteredCoverGalleryAssets, [deferredCoverSearch, filteredCoverGalleryAssets, coverMoodName]);
  const visibleCoverSongs = useMemo(() => { const source = songFilter === "missing" ? missingCoverSongs : coverPickerSongList; return deferredSongSearch ? source.filter((song) => coverSongMatches(song, deferredSongSearch)) : source; }, [coverPickerSongList, deferredSongSearch, missingCoverSongs, songFilter]);
  const previewEntry = useMemo(() => visibleGalleryAssets.find((entry) => entry.key === previewEntryKey) || recentCoverEntries[0] || coverStats.least || visibleGalleryAssets[0] || null, [coverStats.least, previewEntryKey, recentCoverEntries, visibleGalleryAssets]);
  const previewImageUrl = previewEntry ? previewEntry.asset.url || pixelArtUrl(previewEntry.asset.file) : "";
  const activeTargetSong = selectedCoverSongs[0] || currentSong;

  useEffect(() => { if (previewEntryKey && !visibleGalleryAssets.some((entry) => entry.key === previewEntryKey)) setPreviewEntryKey(""); }, [previewEntryKey, visibleGalleryAssets]);
  useEffect(() => { if (coverGalleryMood === "favorites") setCoverGalleryMood("all"); }, [coverGalleryMood, setCoverGalleryMood]);
  useEffect(() => () => { if (toastTimerRef.current) window.clearTimeout(toastTimerRef.current); }, []);

  function flashCoverToast(message: string) { setCoverToast(message); if (toastTimerRef.current) window.clearTimeout(toastTimerRef.current); toastTimerRef.current = window.setTimeout(() => setCoverToast(""), 2200); }
  async function applyEntry(entry: CoverGalleryEntry) { if (!entry || pixelArtBusy || randomizeDisabled) return; setPreviewEntryKey(entry.key); await Promise.resolve(applyCoverAssetToSelection(entry.asset)); setRecentCoverEntries((current) => [entry, ...current.filter((item) => item.key !== entry.key)].slice(0, 8)); flashCoverToast(`applied ${entry.asset.label}`); }
  async function randomizeWithToast(mood: CoverMood) { if (randomizeDisabled) return; await Promise.resolve(randomizeSelectedCovers(mood)); flashCoverToast(mood === "leastUsed" ? "applied least-used covers" : "randomized selected covers"); }

  return <section className="coverStudioLayout coverStudioCleanLayout">
    <section className="panel coverStudioHero coverStudioCleanHero ambientSurface" style={ambientStyle ?? undefined}><div className="coverStudioHeroText coverStudioCleanHeroText"><p className="eyebrow">cover studio</p><h3>album covers</h3><p>Pick songs on the left, then click any cover to apply it. Clean gallery, less noise.</p></div><div className="coverStudioHeroActions coverStudioCleanActions"><button className="heroMain" type="button" disabled={randomizeDisabled} onClick={() => void randomizeWithToast(coverGalleryMood)}>{pixelArtBusy ? "working..." : `randomize ${selectedCount}`}</button><button type="button" onClick={() => void randomizeWithToast("leastUsed")} disabled={pixelArtBusy || randomizeDisabled}>least used</button><button type="button" onClick={() => void randomizeMissingCovers?.()} disabled={pixelArtBusy || !missingCoverSongs.length}>fix missing {missingCoverSongs.length ? `(${missingCoverSongs.length})` : ""}</button><button type="button" onClick={() => void cleanupCoverCache?.()} disabled={pixelArtBusy}>clean cache</button><button type="button" onClick={() => void rescanPixelArtFolder()} disabled={pixelArtBusy}>rescan</button></div></section>
    {coverToast ? <div className="coverApplyToast" role="status">{coverToast}</div> : null}
    <section className="coverMoodTabs coverMoodTabsClean" aria-label="cover filters">{coverMoodOptions.filter((option) => option.id !== "favorites").map((option) => <button key={option.id} type="button" className={coverGalleryMood === option.id ? "active" : ""} onClick={() => setCoverGalleryMood(option.id)}><span>{option.name || option.label || coverMoodName(option.id)}</span><strong>{coverMoodCounts.get(option.id) ?? 0}</strong></button>)}</section>
    <section className="coverStudioBody coverStudioCleanBody"><aside className="panel coverSelectedSongsPanel coverSelectedSongsPanelClean"><div className="panelHead coverPanelHeadClean"><div><p className="eyebrow">songs</p><h3>{coverSelectedSongIds.length} selected</h3></div><span>{songFilter === "missing" ? `${visibleCoverSongs.length} missing` : visibleCoverSongs.length}</span></div><div className="coverSongSearchWrap"><input className="coverStudioSearchInput" value={songSearch} onChange={(event) => setSongSearch(event.currentTarget.value)} placeholder="search songs" spellCheck={false} /></div><div className="coverSongTools coverSongToolsClean"><button type="button" className={songFilter === "all" ? "active" : ""} onClick={() => setSongFilter("all")}>all</button><button type="button" className={songFilter === "missing" ? "active" : ""} onClick={() => setSongFilter("missing")}>missing {missingCoverSongs.length ? `(${missingCoverSongs.length})` : ""}</button><button type="button" onClick={selectCurrentSongForCovers}>current</button><button type="button" onClick={selectVisibleSongsForCovers}>visible</button><button type="button" onClick={() => setCoverSelectedSongIds([])}>clear</button></div><VirtualCoverSongList songs={visibleCoverSongs} selectedIds={coverSelectedSongIds} CoverComponent={CoverComponent} prettyTitle={prettyTitle} prettyMeta={prettyMeta} toggleCoverSongSelection={toggleCoverSongSelection} /></aside>
      <section className="panel coverGalleryPanel coverGalleryPanelClean"><div className="coverGalleryHeader coverGalleryHeaderClean"><div><p className="eyebrow">gallery</p><h3>{coverMoodName(coverGalleryMood)}</h3></div><span>{visibleGalleryAssets.length}{deferredCoverSearch ? ` / ${filteredCoverGalleryAssets.length}` : ""} shown</span></div><div className="coverGalleryToolbar coverGalleryToolbarClean"><input className="coverStudioSearchInput coverGallerySearchInput" value={coverSearch} onChange={(event) => setCoverSearch(event.currentTarget.value)} placeholder="search covers" spellCheck={false} />{coverSearch ? <button type="button" onClick={() => setCoverSearch("")}>clear</button> : null}</div><div className="coverQuickApplyBar"><div className="coverQuickPreview" aria-label="cover preview"><CoverComponent song={activeTargetSong ?? currentSong} className="coverStudioMiniSongArt" /><span aria-hidden="true">→</span>{previewEntry ? <CoverGalleryImage src={previewImageUrl} label={previewEntry.asset.label} priority /> : <div className="coverPreviewEmpty">♪</div>}<button type="button" disabled={!previewEntry || pixelArtBusy || randomizeDisabled} onClick={() => previewEntry && void applyEntry(previewEntry)}>apply preview</button></div>{recentCoverEntries.length ? <div className="coverRecentInline" aria-label="recent covers"><strong>recent</strong>{recentCoverEntries.slice(0, 5).map((entry) => <button key={entry.key} type="button" onClick={() => void applyEntry(entry)} title={`apply ${entry.asset.label}`}><CoverGalleryImage src={entry.asset.url || pixelArtUrl(entry.asset.file)} label={entry.asset.label} /></button>)}</div> : null}</div><VirtualCoverGalleryGrid entries={visibleGalleryAssets} pixelArtBusy={pixelArtBusy} pixelArtUrl={pixelArtUrl} coverMoodName={coverMoodName} onPreviewCover={(entry) => setPreviewEntryKey(entry.key)} onApplyCover={applyEntry} togglePixelCoverExcluded={togglePixelCoverExcluded} /></section>
    </section>
  </section>;
}
