import type { PixelArtBridgeAsset, PixelArtAsset, RuntimePixelArtAsset } from "./cover.types";
import { discordKeyFromFileName } from "../discord/discord.utils";
export const PIXEL_COVER_FAVORITES_STORAGE_KEY = "localitfy.pixelCoverFavorites";
export const PIXEL_COVER_EXCLUDED_STORAGE_KEY = "localitfy.pixelCoverExcluded";
export const PIXEL_ART_CACHE_TTL_MS = 30 * 60 * 1000;
export const PIXEL_ART_LIBRARY: PixelArtAsset[] = ["2cats.jpg","2tankpeople.jpg","4glasses.jpg","animepixell.jpg","animepixel.jpg","beach house.jpg","blackcat.jpg","blackcatlaying.jpg","callhello.jpg","catinspace.jpg","catquestion.jpg","content.png","earthglow.jpg","erikaringingyobell.jpg","gumballl.jpg","marie.jpg","mikuinfortnite.jpg","mikuuu.gif","mitapixel.jpg","peaceanime.jpg","smallcatwithwand.jpg","smallmita.jpg","somegirl.jpg","somegirllooking.jpg","spaceearth.jpg","spacemetor.gif","starpersonlookup.jpg"].map((file)=>({file,label:file.replace(/\.[a-z0-9]+$/i,"").replace(/[_-]+/g," ").replace(/\s+/g," ").trim(),discordKey:discordKeyFromFileName(file)}));
export function normalizePixelArtFileName(asset: PixelArtBridgeAsset,index:number){const pathName=String(asset.path||"").split(/[\\/]/).pop()||"";const name=String(asset.name||asset.key||"pixel").trim();return pathName||`${name||`pixel-${index+1}`}.jpg`;}
export const pixelArtUrl=(file:string)=>{const encoded=encodeURIComponent(file);if(typeof window!=="undefined"&&window.location?.href){try{return new URL(`pixelart/${encoded}`,window.location.href).toString();}catch{return `pixelart/${encoded}`;}}return `pixelart/${encoded}`;};
export const DEFAULT_RUNTIME_PIXEL_ART_ASSETS: RuntimePixelArtAsset[]=PIXEL_ART_LIBRARY.map((asset)=>({...asset,url:pixelArtUrl(asset.file)}));
let runtimePixelArtAssetsCache: RuntimePixelArtAsset[]=DEFAULT_RUNTIME_PIXEL_ART_ASSETS;
export function getCachedRuntimePixelArtAssets(){return runtimePixelArtAssetsCache.length?runtimePixelArtAssetsCache:DEFAULT_RUNTIME_PIXEL_ART_ASSETS;}
export function buildRuntimePixelArtAssets(assets?:PixelArtBridgeAsset[]):RuntimePixelArtAsset[]{if(!Array.isArray(assets)||!assets.length)return getCachedRuntimePixelArtAssets();const assetByName=new Map(PIXEL_ART_LIBRARY.map((asset)=>[asset.file.toLowerCase(),asset]));const runtimeAssets=assets.map((asset,index)=>{const fileName=normalizePixelArtFileName(asset,index);const fallback=PIXEL_ART_LIBRARY[index%PIXEL_ART_LIBRARY.length];const base=assetByName.get(fileName.toLowerCase())||fallback;const label=String(asset.name||base.label||fileName.replace(/\.[a-z0-9]+$/i,"")).trim();const runtimeDiscordKey=discordKeyFromFileName(String(asset.key||fileName||label||base.discordKey));return{...base,file:fileName||base.file,label:label||base.label,discordKey:runtimeDiscordKey||base.discordKey,path:String(asset.path||""),url:String(asset.url||pixelArtUrl(fileName||base.file))};}).filter((asset)=>Boolean(asset.file&&asset.url));if(runtimeAssets.length)runtimePixelArtAssetsCache=runtimeAssets;return getCachedRuntimePixelArtAssets();}
export function runtimePixelArtImageUrl(asset?:RuntimePixelArtAsset|PixelArtAsset|null){if(!asset)return"";const runtime=asset as RuntimePixelArtAsset;return String(runtime.url||(runtime.file?pixelArtUrl(runtime.file):"")).trim();}
export function cleanStringList(value:unknown){if(!Array.isArray(value))return[];const seen=new Set<string>();const output:string[]=[];value.forEach((item)=>{const key=String(item||"").trim();if(!key||seen.has(key))return;seen.add(key);output.push(key);});return output;}
export function getPixelArtAssetKey(asset:RuntimePixelArtAsset){return String(asset.path||asset.url||(asset.file?pixelArtUrl(asset.file):asset.label)||"").trim();}
