import type { Settings } from "../settings.types";
import type { DiagnosticsInfo, PlatformInfoLike, SongLike, UpdateSetting } from "../settings.shared";
import { ToggleRow } from "../settings.shared";
import type { UpdatePromptState } from "../../updates/update.types";
const DANGER_MASCOT_SRC = new URL("../../../assets/danger-state.png", import.meta.url).href;

export type AdvancedSettingsProps = {
  settings: Settings; updateSetting: UpdateSetting; appVersion: string; diagnosticsInfo: DiagnosticsInfo; diagnosticsCopied: boolean; copyDiagnosticsInfo: () => void;
  updatePrompt: UpdatePromptState; manualUpdateCheck: () => void; askUpdaterToInstall: () => void; libraryScanBusy: boolean; rebuildSearchIndexAction: () => void;
  libraryRenderLimitRef: { current: number }; initialLibraryRenderLimit: number; setLibraryRenderLimit: (value: number) => void;
  pixelArtBusy: boolean; songs: ReadonlyArray<SongLike>; randomizeAllCovers: () => void; rescanPixelArtFolder: () => void; changeView: (view: string, source?: string) => void;
  platformInfo: Required<PlatformInfoLike>; resetDiscordSettings: () => void; resetAppearanceSettings: () => void; resetPlayerLayoutSettings: () => void; resetLibraryLayoutSettings: () => void; resetAllSettingsSafely: () => void;
};
export default function AdvancedSettings(p: AdvancedSettingsProps) {
  const notes = p.platformInfo.linuxInstallNotes || [];
  return <section className="settingsCategoryPage settingsDeclutterPageV491 settingsAdvancedBoringV491" aria-label="Advanced settings"><div className="settingsCategoryHeader settingsCategoryHeaderCleanV491"><div><p className="eyebrow">advanced</p><h4>maintenance</h4></div><span>boring tools · version {p.appVersion}</span></div>
    <div className="settingsPanelCard settingsBoringPanelV491 settingsDiagnosticsPanelV491"><div className="settingsPanelHeader settingsDiagnosticsHeader"><div><strong>Diagnostics</strong><span>Safe app info for bug reports. Hidden here so normal settings stay clean.</span></div><button className="settingsActionButton settingsCopyInfoButton" type="button" onClick={p.copyDiagnosticsInfo}>{p.diagnosticsCopied ? "copied" : "copy app info"}</button></div><div className="settingsDiagnosticsGrid settingsDiagnosticsGridV440">{p.diagnosticsInfo.items.map((item) => <div className="settingsDiagnosticCard" key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></div>
    <div className="settingsTwoColumn settingsAdvancedGridV491"><div className="settingsPanelCard settingsBoringPanelV491"><div className="settingsPanelHeader"><div><strong>Update tools</strong><span>Manual update checks and install controls live here.</span></div></div><div className="settingsActionRow settingsActionRowCleanV491"><button className="settingsActionButton" type="button" onClick={p.manualUpdateCheck} disabled={p.updatePrompt.status === "checking" || p.updatePrompt.status === "downloading"}>force update check</button><button className="settingsActionButton" type="button" onClick={p.askUpdaterToInstall} disabled={p.updatePrompt.status !== "downloaded"}>restart to install</button></div></div><div className="settingsPanelCard settingsBoringPanelV491"><div className="settingsPanelHeader"><div><strong>Search and library</strong><span>Repair library loading when something looks stale.</span></div></div><div className="settingsActionRow settingsActionRowCleanV491"><button className="settingsActionButton" type="button" disabled={p.libraryScanBusy} onClick={p.rebuildSearchIndexAction}>rebuild search</button><button className="settingsActionButton" type="button" onClick={() => { p.libraryRenderLimitRef.current = p.initialLibraryRenderLimit; p.setLibraryRenderLimit(p.initialLibraryRenderLimit); }}>reset loaded songs</button></div></div></div>
    <div className="settingsPanelCard settingsBoringPanelV491 settingsFullWidthPanel settingsAdvancedVisualPanelV491"><div className="settingsPanelHeader"><div><strong>Advanced visual tuning</strong><span>Small visual options are hidden here instead of crowding Appearance.</span></div></div><div className="settingsMiniGrid appearanceMiniGridV356"><ToggleRow label="Right side cards" help="Shows the optional right column." checked={p.settings.showRightColumn} onChange={(value) => void p.updateSetting("showRightColumn", value)} /><ToggleRow label="Compact library" help="Fits smaller rows." checked={p.settings.denseList} onChange={(value) => void p.updateSetting("denseList", value)} /><ToggleRow label="Reduce motion" help="Turns off most decorative animations." checked={p.settings.reducedMotion} onChange={(value) => void p.updateSetting("reducedMotion", value)} /><ToggleRow label="Soft corners" help="Uses rounder cards and buttons." checked={p.settings.softCorners} onChange={(value) => void p.updateSetting("softCorners", value)} /><ToggleRow label="Animated glow" help="Keeps ambience on, but pauses it during fast screen switches." checked={p.settings.animatedGlow} onChange={(value) => void p.updateSetting("animatedGlow", value)} /><ToggleRow label="Cat buddy" help="Tiny cat follows your cursor." checked={p.settings.catBuddyEnabled === true} onChange={(value) => void p.updateSetting("catBuddyEnabled", value)} /></div></div>
    <div className="settingsPanelCard settingsBoringPanelV491 settingsFullWidthPanel settingsAdvancedCoverPanelV491"><div className="settingsPanelHeader"><div><strong>Advanced cover repair</strong><span>Bulk cover tools are here so the normal Covers page stays simple.</span></div></div><div className="settingsActionRow settingsActionRowCleanV491"><button className="settingsActionButton" type="button" disabled={p.pixelArtBusy || p.songs.length === 0} onClick={p.randomizeAllCovers}>bulk cover cleanup</button><button className="settingsActionButton" type="button" disabled={p.pixelArtBusy} onClick={p.rescanPixelArtFolder}>repair / rescan covers</button><button className="settingsActionButton" type="button" onClick={() => p.changeView("covers", "advanced")}>hidden covers</button><button className="settingsActionButton" type="button" onClick={() => p.changeView("covers", "advanced")}>least-used cover logic</button></div></div>
    <div className="settingsPanelCard settingsBoringPanelV491 settingsFullWidthPanel"><div className="settingsPanelHeader"><div><strong>{p.platformInfo.desktopControlsLabel}</strong><span>{p.platformInfo.desktopControlsHelp}</span></div></div><div className="settingsMiniGrid"><ToggleRow label="Keep localtify in tray when closed" help="The X button hides the app instead of quitting. Use Quit from the tray to close it fully." checked={p.settings.minimizeToTray} onChange={(value) => void p.updateSetting("minimizeToTray", value)} />{p.platformInfo.startupSettingSupported ? <ToggleRow label={p.platformInfo.startupSettingLabel} help={p.platformInfo.startupSettingHelp} checked={p.settings.startWithWindows} onChange={(value) => void p.updateSetting("startWithWindows", value)} /> : <div className="settingsManualNoteV491"><strong>{p.platformInfo.startupSettingLabel}</strong><span>{p.platformInfo.startupSettingHelp}</span></div>}</div>{(p.platformInfo.id === "linux" || notes.length > 0) ? <ul className="settingsPlainList settingsReleaseList settingsLinuxNotesV491">{notes.map((note) => <li key={note}>{note}</li>)}</ul> : null}</div>
    <div className="settingsPanelCard settingsBoringPanelV491 settingsFullWidthPanel settingsResetPanel settingsDangerPanelV491 settingsDangerMascotPanelV501"><div className="settingsPanelHeader settingsDangerMascotHeaderV501"><img className="settingsDangerMascotV501" src={DANGER_MASCOT_SRC} alt="" draggable={false} aria-hidden="true" /><div><strong>Danger / reset tools</strong><span>Reset only the selected app settings. Your songs stay in the library.</span></div></div><div className="settingsResetGrid"><button className="settingsResetButton" type="button" onClick={p.resetDiscordSettings}><strong>Reset Discord settings</strong><span>Restores privacy mode, status text, buttons, artwork, and cleanup.</span></button><button className="settingsResetButton" type="button" onClick={p.resetAppearanceSettings}><strong>Reset appearance</strong><span>Restores theme, colors, motion, corners, and ambience settings.</span></button><button className="settingsResetButton" type="button" onClick={p.resetPlayerLayoutSettings}><strong>Reset player layout</strong><span>Restores player size, visualizer, volume, and speed.</span></button><button className="settingsResetButton" type="button" onClick={p.resetLibraryLayoutSettings}><strong>Reset library layout</strong><span>Restores sidebar width, compact library, home layout, and hero options.</span></button><button className="settingsResetButton danger" type="button" onClick={p.resetAllSettingsSafely}><strong>Reset all settings</strong><span>Asks first, then restores every app setting to default.</span></button></div></div>
  </section>;
}
